part2/quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('quote/', views.quote, name='quote'),
    path('tag/', views.tag, name='tag'),
    path('author/', views.author, name='author'),
    path('<str:author>', views.detail_author, name='detail_author'),
    path('tag/<str:tag_name>/', views.quotes_by_tag, name='quotes_by_tag'),
]

part2/quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
]

part2/quotes/users/urls.py
from django.conf import settings
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

part2/quotes/quoteapp/models.py
from django.db import models

from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    fullname = models.CharField(max_length=100)
    born_date = models.CharField()
    born_location = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
    

class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=60)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.author.fullname} - {self.quote[:50]}"
    

part2/quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Author, Quote, Tag


class AuthorForm(ModelForm):

    fullname = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    born_date = CharField(min_length=3, max_length=25, widget=TextInput())
    born_location = CharField(min_length=3, max_length=25, widget=TextInput())
    description = CharField(min_length=3, widget=TextInput())
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):

    quote = CharField(min_length=10, max_length=150, required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['author', 'tags']


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

part2/quotes/quoteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Quote, Tag, Author
from .forms import QuoteForm, AuthorForm, TagForm

def main(request):
    quotes =  Quote.objects.all()
    context = {"quotes":quotes}

    return render(request, 'quoteapp/index.html', context)

def quotes_by_tag(request, tag_name):
    tag = get_object_or_404(Tag, name=tag_name)
    quotes = Quote.objects.filter(tags=tag)
    context = {"quotes": quotes, "tag": tag}
    
    return render(request, 'quoteapp/index.html', context)

def detail_author(request, author):
    author_inf = get_object_or_404(Author, fullname=author)
    return render(request, 'quoteapp/authorinfo.html', {"author": author_inf})

@login_required
def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            # new_quote.user = request.user
            new_quote.save()

            choice_author = Author.objects.filter(fullname__in=request.POST.getlist('author'))
            for author in choice_author.iterator():
                new_quote.author = author

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            new_quote.save()


            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/quote.html', {"tags": tags,"authors":authors, 'form': form})

    return render(request, 'quoteapp/quote.html', {"tags": tags, "authors":authors, 'form': QuoteForm()})

@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/tag.html', {'form': form})

    return render(request, 'quoteapp/tag.html', {'form': TagForm()})

@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            if not Author.objects.filter(fullname=form.cleaned_data['fullname']).exists():
                form.save()
                return redirect(to='quoteapp:main')
            else:
                return render(request, 'quoteapp/author.html', {'form': form})

    return render(request, 'quoteapp/author.html', {'form': AuthorForm()})

part2/quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

part2/quotes/quoteapp/templates/quoteapp/authorinfo.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div>
    <div>
        {{ author.fullname }}
    </div>
    <div>
        Born: {{ author.born_date }} {{ author.born_location }}
    </div>
    <div>
        {{ author.description }}
    </div>
</div>

{% endblock %}

part2/quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'noteapp/style.css' %}">
</head>

<body>
    <main class="container">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            {% if user.is_authenticated %}

            <ul>
                <li>Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>
            {% else %}
            <ul>
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>
            {% endif %}
        </nav>

        {% block content %} {% endblock %}
    </main>
</body>

</html>

part2/quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
</head>

<body>
    <main class="container">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            {% if user.is_authenticated %}
                
            <ul>
                <li><a href="{% url 'quoteapp:quote' %}" role="button">Add quote</a></li>
                <li><a href="{% url 'quoteapp:tag' %}" role="button">Add tag</a></li>
                <li><a href="{% url 'quoteapp:author' %}" role="button">Add author</a></li>
                <li>Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>
            {% else %}
            <ul>
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>
            {% endif %}
        </nav>

        <div>
            {% for quote in quotes %}
            <div>
                <span>{{ quote.quote }}</span>
                <span>
                    by
                    <small>{{ quote.author }}</small>
                    <a href="{% url 'quoteapp:detail_author' quote.author %}">(about)</a>
                </span>
                <div>
                    Tags:
                    {% for tag in quote.tags.all %}
                    <a href="{% url 'quoteapp:quotes_by_tag' tag.name %}">{{ tag.name }}</a>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </main>
</body>

</html>

part2/quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote description:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select Autors:
            <select name="author" multiple="multiple" required>
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

part2/quotes/quoteapp/templates/quoteapp/quotes-by-tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div>
    {% for quote in quotes %}
    <div>
        <span>{{ quote.quote }}</span>
        <span>
            by
            <small>{{ quote.author }}</small>
            <a href="{% url 'quoteapp:detail_author' quote.author %}">(about)</a>
        </span>
        <div>
            Tags:
            {% for tag in quote.tags.all %}
            <a href="">{{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

part2/quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}